import type {
  ActivityItem,
  HeaderState,
  MetricCard,
  OpportunityRecord,
  ProjectRecord,
  ReviewItem,
  TaskRecord,
  WorkflowRecord,
} from "@/lib/types";

export const headerState: HeaderState = {
  activeProject: "Delta Launch System",
  activeWorkflow: "Website",
  nextActionCount: 6,
  pendingApprovals: 3,
  blockers: 2,
};

export const tasks: TaskRecord[] = [
  {
    id: "task-001",
    title: "Approve homepage messaging revision",
    status: "Review",
    priority: "Critical",
    dueDate: "Today, 16:00",
    owner: "Alex",
    linkedProject: "Delta Launch System",
    linkedWorkflow: "Website",
    linkedOpportunityOrClient: "Delta Labs",
    notes: "Messaging is ready for final strategic review before the wireframe lock.",
    source: "system",
    nextAction: true,
  },
  {
    id: "task-002",
    title: "Create outreach list for dormant leads",
    status: "To Do",
    priority: "High",
    dueDate: "Tomorrow, 11:00",
    owner: "Dana",
    linkedOpportunityOrClient: "Dormant pipeline",
    notes: "Manual outreach reminder task for reactivation sprint.",
    source: "manual",
    nextAction: false,
  },
  {
    id: "task-003",
    title: "Review Skill Factory API dependency flags",
    status: "Inbox",
    priority: "High",
    dueDate: "Today, 18:00",
    owner: "Blake",
    linkedWorkflow: "Skill Factory Review",
    notes: "Three candidates need dependency confirmation before disposition.",
    source: "system",
    nextAction: true,
  },
  {
    id: "task-004",
    title: "Draft client follow-up after architecture call",
    status: "In Progress",
    priority: "Medium",
    dueDate: "Tomorrow, 09:30",
    owner: "Sofia",
    linkedProject: "Northstar Intake",
    linkedOpportunityOrClient: "Northstar Health",
    notes: "Standalone follow-up copy draft with no active workflow linkage.",
    source: "manual",
    nextAction: false,
  },
  {
    id: "task-005",
    title: "Resolve review blocker on knowledge ingestion batch",
    status: "Waiting",
    priority: "Medium",
    dueDate: "Mar 15",
    owner: "Iris",
    linkedWorkflow: "Knowledge Review",
    notes: "Awaiting source validation note from operations.",
    source: "system",
    nextAction: false,
  },
  {
    id: "task-006",
    title: "Update next action after client onboarding",
    status: "Completed",
    priority: "Low",
    dueDate: "Mar 12",
    owner: "Dana",
    linkedProject: "Atlas Ops",
    linkedOpportunityOrClient: "Atlas Freight",
    notes: "Completed and retained for operator history.",
    source: "system",
    nextAction: false,
  },
  {
    id: "task-007",
    title: "Prepare finance admin checklist",
    status: "To Do",
    priority: "Low",
    dueDate: "Mar 18",
    owner: "Dana",
    notes: "Manual admin task with no project linkage.",
    source: "manual",
    nextAction: false,
  },
  {
    id: "task-008",
    title: "Review workflow routing blocker for CRM handoff",
    status: "Waiting",
    priority: "High",
    dueDate: "Today, 19:00",
    owner: "Chris",
    linkedProject: "Atlas Ops",
    linkedWorkflow: "Solution Architecture",
    linkedOpportunityOrClient: "Atlas Freight",
    notes: "Blocked pending webhook credential confirmation.",
    source: "system",
    nextAction: true,
  },
  {
    id: "task-009",
    title: "Archive completed proposal notes",
    status: "Archived",
    priority: "Low",
    dueDate: "Mar 10",
    owner: "Dana",
    linkedOpportunityOrClient: "Echo Commerce",
    notes: "Archived standalone operations cleanup task.",
    source: "manual",
    nextAction: false,
  },
  {
    id: "task-010",
    title: "Prepare review packet for knowledge pattern merge",
    status: "Review",
    priority: "Medium",
    dueDate: "Mar 16",
    owner: "Iris",
    linkedWorkflow: "Knowledge Review",
    notes: "Queue for merge candidate review and reference mapping.",
    source: "system",
    nextAction: false,
  },
];

export const projects: ProjectRecord[] = [
  {
    projectId: "proj-001",
    projectName: "Delta Launch System",
    projectStatus: "Active",
    currentPhase: "Website Build Spec",
    ownerRole: "Alex",
    linkedClient: "Delta Labs",
    blockers: 1,
    nextProjectAction: "Finalize homepage structure approval",
    linkedTasks: 8,
  },
  {
    projectId: "proj-002",
    projectName: "Atlas Ops",
    projectStatus: "Implementation",
    currentPhase: "Solution Architecture",
    ownerRole: "Blake",
    linkedClient: "Atlas Freight",
    blockers: 2,
    nextProjectAction: "Resolve CRM credential dependency",
    linkedTasks: 6,
  },
  {
    projectId: "proj-003",
    projectName: "Northstar Intake",
    projectStatus: "Proposal",
    currentPhase: "Evaluation",
    ownerRole: "Alex",
    linkedClient: "Northstar Health",
    blockers: 0,
    nextProjectAction: "Deliver follow-up summary",
    linkedTasks: 3,
  },
  {
    projectId: "proj-004",
    projectName: "Cinder Research Sprint",
    projectStatus: "Complete",
    currentPhase: "Archived Learning",
    ownerRole: "Iris",
    linkedClient: "Cinder Studio",
    blockers: 0,
    nextProjectAction: "None",
    linkedTasks: 1,
  },
];

export const opportunities: OpportunityRecord[] = [
  {
    opportunityId: "opp-001",
    opportunityName: "Delta Labs CRM rebuild",
    pipelineStage: "Proposal",
    owner: "Alex",
    linkedClient: "Delta Labs",
    nextOpportunityAction: "Send scope recap",
    classificationStatus: "Qualified",
    linkedTasks: 4,
  },
  {
    opportunityId: "opp-002",
    opportunityName: "Northstar retention automation",
    pipelineStage: "Lead",
    owner: "Iris",
    linkedClient: "Northstar Health",
    nextOpportunityAction: "Complete opportunity scan",
    classificationStatus: "Under Review",
    linkedTasks: 3,
  },
  {
    opportunityId: "opp-003",
    opportunityName: "Echo Commerce website refresh",
    pipelineStage: "Active",
    owner: "Alex",
    linkedClient: "Echo Commerce",
    nextOpportunityAction: "Prepare offer revision",
    classificationStatus: "Approved",
    linkedTasks: 5,
  },
  {
    opportunityId: "opp-004",
    opportunityName: "Atlas Freight workflow reporting",
    pipelineStage: "Complete",
    owner: "Blake",
    linkedClient: "Atlas Freight",
    nextOpportunityAction: "Transition to delivery archive",
    classificationStatus: "Delivered",
    linkedTasks: 1,
  },
];

export const workflows: WorkflowRecord[] = [
  {
    id: "wf-001",
    activeWorkflow: "Website",
    workflowStatus: "Active",
    currentStep: "Homepage approval",
    blockingIssues: ["Copy sign-off pending from Strategy"],
    nextWorkflowCandidate: "Prototype",
    linkedProject: "Delta Launch System",
    nodes: [
      { id: "n-1", name: "Strategy", type: "System", status: "Complete", summary: "Offer and page direction locked." },
      { id: "n-2", name: "Copy Review", type: "Manual Review", status: "Active", summary: "Headline and CTA edits pending." },
      { id: "n-3", name: "Wireframe", type: "Design", status: "Queued", summary: "Starts after copy approval." },
      { id: "n-4", name: "Prototype", type: "Build", status: "Queued", summary: "Next candidate after wireframe handoff." },
    ],
  },
  {
    id: "wf-002",
    activeWorkflow: "Solution Architecture",
    workflowStatus: "Blocked",
    currentStep: "Credential mapping",
    blockingIssues: ["Webhook access not confirmed", "Sandbox test data missing"],
    nextWorkflowCandidate: "Prototype",
    linkedProject: "Atlas Ops",
    nodes: [
      { id: "n-5", name: "System Scope", type: "System", status: "Complete", summary: "Architecture intent approved." },
      { id: "n-6", name: "Integration Map", type: "API", status: "Active", summary: "Dependency list under review." },
      { id: "n-7", name: "Credential Review", type: "Manual Review", status: "Blocked", summary: "Waiting on ops confirmation." },
      { id: "n-8", name: "Deployment Spec", type: "Build", status: "Queued", summary: "Held until blockers clear." },
    ],
  },
];

export const skillFactoryReview: ReviewItem[] = [
  {
    id: "sf-001",
    title: "Claude automation audit workflow",
    reviewer: "Blake",
    status: "review_pending",
    blockers: ["API rate assumptions need confirmation"],
    summary: ["Candidate classified to Automation domain.", "Dependency burden marked medium.", "Merge candidate for existing audit skill."],
    lastDisposition: "Awaiting human review",
  },
  {
    id: "sf-002",
    title: "Client intake triage rubric",
    reviewer: "Dana",
    status: "approved_with_edits",
    blockers: [],
    summary: ["Operations-aligned draft is normalized.", "Needs owner-role wording cleanup.", "Ready for curated master asset versioning."],
    lastDisposition: "Approved with edits",
  },
  {
    id: "sf-003",
    title: "Growth signal extraction prompt set",
    reviewer: "Mason",
    status: "merge_candidate",
    blockers: ["Knowledge references must be standardized"],
    summary: ["Growth domain fit is strong.", "Potential overlap with existing signal-detection assets."],
    lastDisposition: "Merge candidate",
  },
];

export const knowledgeReview: ReviewItem[] = [
  {
    id: "kr-001",
    title: "Conversion benchmark packet",
    reviewer: "Iris",
    status: "pending",
    blockers: ["NotebookLM evidence links incomplete"],
    summary: ["Research evidence imported.", "Structured vault placement proposed.", "Needs source completeness check."],
    lastDisposition: "Pending review",
  },
  {
    id: "kr-002",
    title: "Operations handoff heuristics",
    reviewer: "Dana",
    status: "approved",
    blockers: [],
    summary: ["Knowledge path validated.", "Reference map updated.", "Ready for canonical vault entry."],
    lastDisposition: "Approved",
  },
  {
    id: "kr-003",
    title: "AI workflow monitoring checklist",
    reviewer: "Chris",
    status: "reference_only",
    blockers: ["Third-party pricing assumptions not stable"],
    summary: ["Retained for reference only.", "Not appropriate for canonical merge yet."],
    lastDisposition: "Reference only",
  },
];

export const activityFeed: ActivityItem[] = [
  {
    id: "act-001",
    activityType: "Controlled Write-Back",
    activityTime: "2 min ago",
    linkedDomain: "Action Queue",
    linkedRecord: "task-002",
    operatorOrSystemSource: "Dana",
    summary: "Manual outreach task created for dormant pipeline review.",
  },
  {
    id: "act-002",
    activityType: "Workflow Activity",
    activityTime: "11 min ago",
    linkedDomain: "Workflow Progress",
    linkedRecord: "wf-001",
    operatorOrSystemSource: "System",
    summary: "Website workflow advanced to homepage approval.",
  },
  {
    id: "act-003",
    activityType: "Review Activity",
    activityTime: "25 min ago",
    linkedDomain: "Skill Factory Review",
    linkedRecord: "sf-002",
    operatorOrSystemSource: "Dana",
    summary: "Skill candidate moved to approved_with_edits.",
  },
  {
    id: "act-004",
    activityType: "Memory Activity",
    activityTime: "41 min ago",
    linkedDomain: "Project State",
    linkedRecord: "proj-002",
    operatorOrSystemSource: "System",
    summary: "Operational summary updated with new credential blocker.",
  },
  {
    id: "act-005",
    activityType: "Reminder Activity",
    activityTime: "1 hr ago",
    linkedDomain: "Reminder State",
    linkedRecord: "rem-014",
    operatorOrSystemSource: "System",
    summary: "Client follow-up reminder deferred to tomorrow morning.",
  },
  {
    id: "act-006",
    activityType: "Review Activity",
    activityTime: "2 hr ago",
    linkedDomain: "Knowledge Review",
    linkedRecord: "kr-002",
    operatorOrSystemSource: "Iris",
    summary: "Knowledge ingestion item approved for vault merge.",
  },
];

export const metrics: MetricCard[] = [
  { id: "m-1", label: "Open tasks", value: "23", trend: "-8% vs last week", context: "Unified queue across system and manual work." },
  { id: "m-2", label: "Next actions", value: "6", trend: "+1 today", context: "Immediate operator actions needing attention." },
  { id: "m-3", label: "Pending reviews", value: "7", trend: "2 high priority", context: "Combined Skill Factory and Knowledge review load." },
  { id: "m-4", label: "Workflow health", value: "82%", trend: "2 blockers active", context: "Active workflows with documented next stages." },
  { id: "m-5", label: "Lead conversion", value: "31%", trend: "+4% this month", context: "Qualified opportunities reaching proposal." },
  { id: "m-6", label: "On-time completion", value: "88%", trend: "Stable", context: "Tasks completed before due date this cycle." },
];
