import type {
  ActivityItem,
  HeaderState,
  MetricCard,
  OpportunityRecord,
  ProjectRecord,
  ReviewItem,
  TaskRecord,
  WorkflowRecord,
} from "@/lib/types";

export const headerState: HeaderState = {
  activeProject: "Harbour City Rentals",
  activeWorkflow: "Harbour Booking Flow",
  nextActionCount: 5,
  pendingApprovals: 7,
  blockers: 2,
};

export const tasks: TaskRecord[] = [
  {
    id: "task-001",
    title: "Finalize Northshore consultation qualification rules",
    status: "In Progress",
    priority: "High",
    dueDate: "Today",
    owner: "Yan",
    linkedProject: "Northshore Aesthetics",
    linkedWorkflow: "Northshore Lead Recovery",
    linkedOpportunityOrClient: "Northshore Aesthetics",
    notes: "Tighten the high-intent consultation routing conditions before final approval.",
    source: "manual",
    nextAction: false,
  },
  {
    id: "task-002",
    title: "QA Harbour Rentals property availability lookup logic",
    status: "In Progress",
    priority: "High",
    dueDate: "Today",
    owner: "Yan",
    linkedProject: "Harbour City Rentals",
    linkedWorkflow: "Harbour Booking Flow",
    linkedOpportunityOrClient: "Harbour City Rentals",
    notes: "Confirm unavailable-unit fallback behavior and booking-link handoff.",
    source: "manual",
    nextAction: false,
  },
  {
    id: "task-003",
    title: "Review Apex investor FAQ ingestion confidence thresholds",
    status: "Review",
    priority: "High",
    dueDate: "Today",
    owner: "Yan",
    linkedProject: "Apex Property Partners",
    linkedWorkflow: "Apex Investor Enquiry Flow",
    linkedOpportunityOrClient: "Apex Property Partners",
    notes: "Two FAQ answer paths are still classifying below target confidence.",
    source: "manual",
    nextAction: false,
  },
  {
    id: "task-004",
    title: "Reclassify Harbour guest enquiry transcript batch",
    status: "Completed",
    priority: "Medium",
    dueDate: "Today",
    owner: "System",
    linkedProject: "Harbour City Rentals",
    linkedWorkflow: "Knowledge Review",
    linkedOpportunityOrClient: "Harbour City Rentals",
    notes: "Four new WhatsApp enquiries were re-labeled and queued for downstream QA.",
    source: "system",
    nextAction: false,
  },
  {
    id: "task-005",
    title: "Validate Northshore missed-call recovery follow-up timing",
    status: "In Progress",
    priority: "Medium",
    dueDate: "Tomorrow",
    owner: "Yan",
    linkedProject: "Northshore Aesthetics",
    linkedWorkflow: "Northshore Lead Recovery",
    linkedOpportunityOrClient: "Northshore Aesthetics",
    notes: "Compare 10-minute versus 20-minute first-touch recovery performance.",
    source: "manual",
    nextAction: false,
  },
  {
    id: "task-006",
    title: "Approve Harbour automated booking-link message format",
    status: "Review",
    priority: "Critical",
    dueDate: "Today",
    owner: "Yan",
    linkedProject: "Harbour City Rentals",
    linkedWorkflow: "Harbour Booking Flow",
    linkedOpportunityOrClient: "Harbour City Rentals",
    notes: "Final review needed before enabling the live reminder sequence.",
    source: "system",
    nextAction: true,
  },
  {
    id: "task-007",
    title: "Send Verity Wealth proposal follow-up",
    status: "To Do",
    priority: "High",
    dueDate: "Today",
    owner: "Yan",
    linkedOpportunityOrClient: "Verity Wealth Partners",
    notes: "Proposal has been open for three business days without response.",
    source: "manual",
    nextAction: true,
  },
  {
    id: "task-008",
    title: "Approve Northshore review-request automation wording",
    status: "Review",
    priority: "High",
    dueDate: "Tomorrow",
    owner: "Yan",
    linkedProject: "Northshore Aesthetics",
    linkedWorkflow: "Northshore Lead Recovery",
    linkedOpportunityOrClient: "Northshore Aesthetics",
    notes: "Final tone pass required before rollout.",
    source: "system",
    nextAction: true,
  },
  {
    id: "task-009",
    title: "Review Solara Dental discovery notes before proposal drafting",
    status: "Review",
    priority: "High",
    dueDate: "Tomorrow",
    owner: "Yan",
    linkedOpportunityOrClient: "Solara Dental Studio",
    notes: "Discovery summary is ready for scope shaping.",
    source: "manual",
    nextAction: true,
  },
  {
    id: "task-010",
    title: "Confirm Apex inactive-investor re-engagement sequence",
    status: "Review",
    priority: "High",
    dueDate: "Tomorrow",
    owner: "Yan",
    linkedProject: "Apex Property Partners",
    linkedWorkflow: "Apex Investor Enquiry Flow",
    linkedOpportunityOrClient: "Apex Property Partners",
    notes: "Sequence timing and CTA need sign-off.",
    source: "system",
    nextAction: true,
  },
  {
    id: "task-011",
    title: "Await Harbour Rentals calendar API credentials",
    status: "Waiting",
    priority: "Critical",
    dueDate: "Open",
    owner: "Client",
    linkedProject: "Harbour City Rentals",
    linkedWorkflow: "Harbour Booking Flow",
    linkedOpportunityOrClient: "Harbour City Rentals",
    notes: "Live booking confirmation cannot be enabled until credentials are provided.",
    source: "system",
    nextAction: false,
  },
  {
    id: "task-012",
    title: "Await Northshore receptionist FAQ approval",
    status: "Waiting",
    priority: "Medium",
    dueDate: "Open",
    owner: "Client",
    linkedProject: "Northshore Aesthetics",
    linkedWorkflow: "Knowledge Review",
    linkedOpportunityOrClient: "Northshore Aesthetics",
    notes: "Client must confirm two revised policy responses.",
    source: "system",
    nextAction: false,
  },
  {
    id: "task-013",
    title: "Await Apex outbound tone-rule sign-off",
    status: "Waiting",
    priority: "Medium",
    dueDate: "Open",
    owner: "Client",
    linkedProject: "Apex Property Partners",
    linkedWorkflow: "Apex Investor Enquiry Flow",
    linkedOpportunityOrClient: "Apex Property Partners",
    notes: "Investor nurture wording still needs owner approval.",
    source: "system",
    nextAction: false,
  },
  {
    id: "task-014",
    title: "Await Titan Roofing scope revision response",
    status: "Waiting",
    priority: "Medium",
    dueDate: "Open",
    owner: "Yan",
    linkedOpportunityOrClient: "Titan Roofing Group",
    notes: "Follow-up sent; waiting on revised service package decision.",
    source: "system",
    nextAction: false,
  },
  {
    id: "task-015",
    title: "New Harbour guest enquiry transcripts ready for classification",
    status: "Inbox",
    priority: "Medium",
    dueDate: "Today",
    owner: "System",
    linkedWorkflow: "Knowledge Review",
    linkedOpportunityOrClient: "Harbour City Rentals",
    notes: "Recent WhatsApp enquiries exceed confidence review threshold.",
    source: "system",
    nextAction: false,
  },
  {
    id: "task-016",
    title: "New Northshore call-script PDF ready for knowledge review",
    status: "Review",
    priority: "Medium",
    dueDate: "Today",
    owner: "System",
    linkedWorkflow: "Knowledge Review",
    linkedOpportunityOrClient: "Northshore Aesthetics",
    notes: "Candidate source detected for receptionist FAQ and escalation logic.",
    source: "system",
    nextAction: false,
  },
  {
    id: "task-017",
    title: "New Apex investor onboarding doc ready for ingestion",
    status: "Review",
    priority: "Medium",
    dueDate: "Tomorrow",
    owner: "System",
    linkedWorkflow: "Knowledge Review",
    linkedOpportunityOrClient: "Apex Property Partners",
    notes: "Possible new knowledge entries for checklist and FAQ handling.",
    source: "system",
    nextAction: false,
  },
  {
    id: "task-018",
    title: "Opportunity notes added from Ember Fitness outbound research",
    status: "Archived",
    priority: "Low",
    dueDate: "Tomorrow",
    owner: "Yan",
    linkedOpportunityOrClient: "Ember Fitness Collective",
    notes: "Discovery prep notes were captured and archived to the prospect record.",
    source: "system",
    nextAction: false,
  },
  {
    id: "task-019",
    title: "Resolve Harbour booking reminder failure in staging",
    status: "In Progress",
    priority: "Critical",
    dueDate: "Today",
    owner: "Yan",
    linkedProject: "Harbour City Rentals",
    linkedWorkflow: "Harbour Booking Flow",
    linkedOpportunityOrClient: "Harbour City Rentals",
    notes: "Reminder job is not firing after booking-link issuance in one test branch.",
    source: "system",
    nextAction: false,
  },
  {
    id: "task-020",
    title: "Resolve Titan Roofing SMTP credential blocker",
    status: "To Do",
    priority: "Critical",
    dueDate: "Today",
    owner: "Yan",
    linkedOpportunityOrClient: "Titan Roofing Group",
    notes: "Email follow-up step cannot proceed without verified domain configuration.",
    source: "manual",
    nextAction: false,
  },
];

export const projects: ProjectRecord[] = [
  {
    projectId: "proj-001",
    projectName: "Northshore Aesthetics",
    projectStatus: "Build",
    currentPhase: "Lead Capture Automation",
    ownerRole: "Yan",
    linkedClient: "Northshore Aesthetics",
    blockers: 0,
    nextProjectAction: "Approve review-request wording",
    linkedTasks: 6,
    progress: 72,
  },
  {
    projectId: "proj-002",
    projectName: "Harbour City Rentals",
    projectStatus: "QA",
    currentPhase: "Booking Automation QA",
    ownerRole: "Yan",
    linkedClient: "Harbour City Rentals",
    blockers: 1,
    nextProjectAction: "Resolve reminder failure in staging",
    linkedTasks: 7,
    progress: 78,
  },
  {
    projectId: "proj-003",
    projectName: "Apex Property Partners",
    projectStatus: "Implementation",
    currentPhase: "Investor Enquiry Routing",
    ownerRole: "Yan",
    linkedClient: "Apex Property Partners",
    blockers: 1,
    nextProjectAction: "Tune FAQ confidence thresholds",
    linkedTasks: 5,
    progress: 64,
  },
];

export const opportunities: OpportunityRecord[] = [
  {
    opportunityId: "opp-001",
    opportunityName: "Solara Dental Studio",
    pipelineStage: "Discovery",
    owner: "Yan",
    linkedClient: "Dental lead capture + booking automation",
    nextOpportunityAction: "Validate discovery notes before proposal drafting",
    classificationStatus: "Discovery Active",
    linkedTasks: 3,
    pipelineValue: "$3,500",
  },
  {
    opportunityId: "opp-002",
    opportunityName: "Verity Wealth Partners",
    pipelineStage: "Proposal Sent",
    owner: "Yan",
    linkedClient: "Investor enquiry + proposal follow-up",
    nextOpportunityAction: "Send proposal follow-up",
    classificationStatus: "Awaiting Response",
    linkedTasks: 2,
    pipelineValue: "$5,000",
  },
  {
    opportunityId: "opp-003",
    opportunityName: "Ember Fitness Collective",
    pipelineStage: "Initial Contact",
    owner: "Yan",
    linkedClient: "Outbound qualification + missed-call recovery",
    nextOpportunityAction: "Turn research notes into first-touch outreach",
    classificationStatus: "Research Complete",
    linkedTasks: 1,
    pipelineValue: "$2,200",
  },
  {
    opportunityId: "opp-004",
    opportunityName: "Titan Roofing Group",
    pipelineStage: "Negotiation",
    owner: "Yan",
    linkedClient: "Lead follow-up + credential-gated email automation",
    nextOpportunityAction: "Resolve SMTP blocker and resend scope revision",
    classificationStatus: "Scope Revision",
    linkedTasks: 2,
    pipelineValue: "$6,500",
  },
];

export const workflows: WorkflowRecord[] = [
  {
    id: "wf-001",
    activeWorkflow: "Northshore Lead Recovery",
    workflowStatus: "Active",
    currentStep: "Review-request wording approval",
    blockingIssues: [],
    nextWorkflowCandidate: "Live enablement",
    linkedProject: "Northshore Aesthetics",
    nodes: [
      { id: "n-1", name: "Missed Call Captured", type: "Signal Detection", status: "Complete", summary: "Inbound call events are being detected and logged." },
      { id: "n-2", name: "Qualification Logic", type: "Routing Rules", status: "Complete", summary: "High-intent consultation conditions are locked in for review." },
      { id: "n-3", name: "Recovery Message", type: "Prompt Variant", status: "Active", summary: "Tone and first-touch timing are under operator QA." },
      { id: "n-4", name: "Review Request", type: "Follow-Up", status: "Queued", summary: "Post-visit review workflow is staged behind wording approval." },
    ],
  },
  {
    id: "wf-002",
    activeWorkflow: "Harbour Booking Flow",
    workflowStatus: "Blocked",
    currentStep: "Reminder sequence QA",
    blockingIssues: ["Reminder job fails after booking-link issuance in staging"],
    nextWorkflowCandidate: "Live booking enablement",
    linkedProject: "Harbour City Rentals",
    nodes: [
      { id: "n-5", name: "Enquiry Captured", type: "Lead Intake", status: "Complete", summary: "Website and WhatsApp enquiries are entering the shared intake queue." },
      { id: "n-6", name: "Qualification", type: "Decision Logic", status: "Complete", summary: "Guest intent and stay-fit signals are routing correctly." },
      { id: "n-7", name: "Availability Lookup", type: "Property Match", status: "Active", summary: "Unavailable-unit fallback and handoff behavior are under QA." },
      { id: "n-8", name: "Booking Link Issued", type: "Booking Automation", status: "Complete", summary: "Qualified guests receive the correct booking path and fallback messaging." },
      { id: "n-9", name: "Follow-Up Reminders", type: "Reminder Job", status: "Blocked", summary: "Reminder step is failing in one staging branch after booking-link send." },
    ],
  },
  {
    id: "wf-003",
    activeWorkflow: "Apex Investor Enquiry Flow",
    workflowStatus: "Active",
    currentStep: "FAQ threshold tuning",
    blockingIssues: ["Outbound tone-rule sign-off pending from client"],
    nextWorkflowCandidate: "Re-engagement rollout",
    linkedProject: "Apex Property Partners",
    nodes: [
      { id: "n-10", name: "Enquiry Routed", type: "Lead Triage", status: "Complete", summary: "Investor enquiries are split by intent and urgency." },
      { id: "n-11", name: "FAQ Answering", type: "Knowledge Assistant", status: "Active", summary: "Low-confidence answers are being reviewed before promotion." },
      { id: "n-12", name: "Investor Routing", type: "Routing Prompt", status: "Queued", summary: "Routing prompt is ready pending tone-rule sign-off." },
      { id: "n-13", name: "Re-Engagement Sequence", type: "Follow-Up", status: "Queued", summary: "Inactive-investor nurture is ready for final timing approval." },
    ],
  },
];

export const skillFactoryReview: ReviewItem[] = [
  {
    id: "sf-001",
    title: "Missed-call recovery prompt variant",
    reviewer: "Yan",
    status: "review_pending",
    blockers: ["Needs final tone approval against Northshore consultation scenarios"],
    summary: ["Candidate variant improves first-touch clarity after missed calls.", "Confidence is high for medical-aesthetic enquiries.", "Ready for decision after final wording pass."],
    lastDisposition: "Awaiting operator review",
  },
  {
    id: "sf-002",
    title: "Booking-enquiry classification prompt",
    reviewer: "Yan",
    status: "approved_with_edits",
    blockers: [],
    summary: ["Harbour guest-intent prompt is classifying booking requests correctly.", "Minor edits were requested for unavailable-unit fallback language.", "Approved for curated prompt packaging after wording update."],
    lastDisposition: "Approved with edits",
  },
  {
    id: "sf-003",
    title: "Property-match recommendation rubric",
    reviewer: "Yan",
    status: "merge_candidate",
    blockers: ["Needs stronger traceability notes for property availability assumptions"],
    summary: ["Rubric supports availability lookup and recommendation scoring.", "Likely merges with the existing booking qualification skill family."],
    lastDisposition: "Merge candidate",
  },
  {
    id: "sf-004",
    title: "Investor enquiry routing prompt",
    reviewer: "Yan",
    status: "review_pending",
    blockers: ["Client tone-rule approval still pending"],
    summary: ["Prompt separates acquisition, documentation, and nurture intents.", "Routing quality is strong but cannot be normalized until tone guidance is signed off."],
    lastDisposition: "Pending tone sign-off",
  },
  {
    id: "sf-005",
    title: "Discovery note summarizer candidate",
    reviewer: "Yan",
    status: "reference_only",
    blockers: ["Output quality is inconsistent across short discovery calls"],
    summary: ["Candidate is useful for operator prep but not yet stable enough for promotion.", "Retained as reference only until summary structure improves."],
    lastDisposition: "Reference only",
  },
];

export const knowledgeReview: ReviewItem[] = [
  {
    id: "kr-001",
    title: "Northshore receptionist call script PDF",
    reviewer: "Yan",
    status: "pending",
    blockers: ["Two policy-response variants need approval before merge"],
    summary: ["Candidate source detected for receptionist FAQ coverage.", "Escalation logic looks usable for live routing support.", "Awaiting final approval on policy wording."],
    lastDisposition: "Pending review",
  },
  {
    id: "kr-002",
    title: "Harbour guest enquiry FAQ",
    reviewer: "Yan",
    status: "pending",
    blockers: ["Availability edge cases still need one more confidence pass"],
    summary: ["FAQ source maps cleanly to guest enquiry and booking-flow support.", "Good fit for knowledge-assistant behavior once edge cases are closed."],
    lastDisposition: "Pending QA",
  },
  {
    id: "kr-003",
    title: "Harbour booking confirmation template",
    reviewer: "Yan",
    status: "approved",
    blockers: [],
    summary: ["Confirmation template is ready for canonical booking handoff guidance.", "Message structure aligns with Harbour follow-up automation requirements."],
    lastDisposition: "Approved",
  },
  {
    id: "kr-004",
    title: "Apex investor FAQ export",
    reviewer: "Yan",
    status: "pending",
    blockers: ["Low-confidence answers remain below ingestion threshold"],
    summary: ["High-value investor FAQs are ready for structured review.", "Threshold tuning is still required before canonization."],
    lastDisposition: "Pending threshold review",
  },
  {
    id: "kr-005",
    title: "Solara discovery call transcript",
    reviewer: "Yan",
    status: "pending",
    blockers: [],
    summary: ["Transcript is ready for scope-shaping and proposal drafting support.", "Can seed both discovery notes and proposal assumptions once approved."],
    lastDisposition: "Awaiting decision",
  },
  {
    id: "kr-006",
    title: "Titan scope revision notes",
    reviewer: "Yan",
    status: "reference_only",
    blockers: ["Commercial terms are still moving during negotiation"],
    summary: ["Useful for internal reference during negotiation.", "Not stable enough for canonical ingestion until scope is locked."],
    lastDisposition: "Reference only",
  },
];

export const activityFeed: ActivityItem[] = [
  {
    id: "act-001",
    activityType: "Workflow Activity",
    activityTime: "4 min ago",
    linkedDomain: "Workflow Progress",
    linkedRecord: "wf-002",
    operatorOrSystemSource: "System",
    summary: "Harbour booking flow flagged a reminder-job failure after booking-link issuance in staging.",
  },
  {
    id: "act-002",
    activityType: "Review Activity",
    activityTime: "12 min ago",
    linkedDomain: "Skill Factory Review",
    linkedRecord: "sf-002",
    operatorOrSystemSource: "Yan",
    summary: "Booking-enquiry classification prompt moved to approved_with_edits.",
  },
  {
    id: "act-003",
    activityType: "Memory Activity",
    activityTime: "27 min ago",
    linkedDomain: "Project State",
    linkedRecord: "proj-001",
    operatorOrSystemSource: "System",
    summary: "Northshore operational memory updated with revised consultation qualification rules.",
  },
  {
    id: "act-004",
    activityType: "Controlled Write-Back",
    activityTime: "41 min ago",
    linkedDomain: "Action Queue",
    linkedRecord: "task-007",
    operatorOrSystemSource: "Yan",
    summary: "Proposal follow-up task created for Verity Wealth after three business days of inactivity.",
  },
  {
    id: "act-005",
    activityType: "Review Activity",
    activityTime: "58 min ago",
    linkedDomain: "Knowledge Review",
    linkedRecord: "kr-003",
    operatorOrSystemSource: "Yan",
    summary: "Harbour booking confirmation template approved for canonical use.",
  },
  {
    id: "act-006",
    activityType: "Reminder Activity",
    activityTime: "1 hr ago",
    linkedDomain: "Reminder State",
    linkedRecord: "task-019",
    operatorOrSystemSource: "System",
    summary: "Retry alert raised after Harbour staging reminder sequence missed the post-link window.",
  },
  {
    id: "act-007",
    activityType: "Workflow Activity",
    activityTime: "2 hr ago",
    linkedDomain: "Workflow Progress",
    linkedRecord: "wf-003",
    operatorOrSystemSource: "System",
    summary: "Apex investor FAQ answers dropped below target confidence and were routed back to review.",
  },
  {
    id: "act-008",
    activityType: "Controlled Write-Back",
    activityTime: "3 hr ago",
    linkedDomain: "Action Queue",
    linkedRecord: "task-001",
    operatorOrSystemSource: "Yan",
    summary: "Northshore qualification-rules task updated after consultation routing edge-case review.",
  },
];

export const metrics: MetricCard[] = [
  { id: "m-1", label: "Follow-up SLA Met", value: "92%", trend: "Above target this week", context: "Lead and proposal follow-up steps are landing inside the current agency response window." },
  { id: "m-2", label: "Avg Task Completion Rate", value: "89%", trend: "Stable over 14 days", context: "Operator-owned and system-generated queue items are closing on schedule." },
  { id: "m-3", label: "Active Clients", value: "3", trend: "Northshore, Harbour, Apex", context: "Current delivery clients across active build, QA, and implementation work." },
  { id: "m-4", label: "Open Opportunities", value: "4", trend: "$17,200 total pipeline", context: "Discovery, proposal, negotiation, and outbound opportunities in the current book." },
  { id: "m-5", label: "Active Workflows", value: "7", trend: "2 under active pressure", context: "Agency workflows currently being monitored across delivery and review operations." },
  { id: "m-6", label: "Pending Reviews", value: "7", trend: "4 knowledge, 3 skill", context: "Combined review load requiring operator attention before promotion or approval." },
  { id: "m-7", label: "Knowledge Items Awaiting Review", value: "11", trend: "Harbour and Apex lead volume up", context: "Pending ingestion candidates across transcripts, templates, and FAQ sources." },
  { id: "m-8", label: "Skills Approved This Week", value: "4", trend: "1 awaiting merge", context: "Prompt and rubric assets promoted through the bounded Skill Factory review path." },
  { id: "m-9", label: "Manual Intervention Rate", value: "13%", trend: "Down 2 points", context: "Share of workflows requiring direct operator recovery or override this cycle." },
  { id: "m-10", label: "Discovery-to-Proposal Conversion", value: "50%", trend: "2 of 4 current prospects", context: "Qualified discovery work turning into commercial proposals at a healthy boutique-agency rate." },
];
