import type {
  ActivityItem,
  AgencyOverviewSummary,
  CampaignRecord,
  DeliveryProgressItem,
  HeaderState,
  MetricCard,
  OpportunityRecord,
  PipelineStageSummary,
  Priority,
  ProjectRecord,
  ReviewItem,
  TaskRecord,
  WorkflowRecord,
} from "@/lib/types";

const priorityRank: Record<Priority, number> = {
  Critical: 4,
  High: 3,
  Medium: 2,
  Low: 1,
};

export const campaigns: CampaignRecord[] = [
  {
    id: "camp-001",
    name: "Bangkok Aesthetic Clinics Outreach",
    segment: "Aesthetic clinics in Bangkok",
    status: "Active",
    owner: "Yan",
    contactsCount: 28,
    notes: "Outbound campaign focused on automation, missed-call recovery, and high-value consultation booking.",
  },
  {
    id: "camp-002",
    name: "Property Management Operators Q2",
    segment: "Property managers and serviced apartment operators",
    status: "Research",
    owner: "Yan",
    contactsCount: 14,
    notes: "Research-heavy segment build to feed upcoming outreach and proposal generation.",
  },
];

export const tasks: TaskRecord[] = [
  {
    id: "task-001",
    title: "Send Smile Dental first follow-up",
    status: "Open",
    priority: "High",
    dueDate: "2026-03-21",
    owner: "Yan",
    ownerType: "Human",
    linkedOpportunityOrClient: "Smile Dental Bangkok",
    notes: "Follow up on the initial outreach email with a discovery-call option.",
    details: "Prospect replied with mild interest and asked for more detail on booking automation.",
    source: "manual",
    nextAction: true,
    category: "Pipeline",
    overdue: false,
  },
  {
    id: "task-002",
    title: "Review prototype direction for Solara Dental",
    status: "Review",
    priority: "Critical",
    dueDate: "2026-03-20",
    owner: "Yan",
    ownerType: "Human",
    linkedProject: "Solara Dental Growth System",
    linkedWorkflow: "Prototype",
    linkedOpportunityOrClient: "Solara Dental Studio",
    notes: "Need sign-off on the first prototype direction before proposal packaging.",
    details: "Check prototype narrative, CTA order, and commercial assumptions before sending.",
    source: "manual",
    nextAction: true,
    category: "Project",
    overdue: false,
  },
  {
    id: "task-003",
    title: "Prepare discovery notes for Verity Wealth",
    status: "In Progress",
    priority: "High",
    dueDate: "2026-03-20",
    owner: "Yan",
    ownerType: "Human",
    linkedProject: "Verity Wealth Evaluation",
    linkedWorkflow: "Evaluation",
    linkedOpportunityOrClient: "Verity Wealth Partners",
    notes: "Turn discovery transcript into evaluation findings and candidate offer direction.",
    details: "This will feed the prototype/proposal decision.",
    source: "manual",
    nextAction: false,
    category: "Project",
    overdue: false,
  },
  {
    id: "task-004",
    title: "Add 15 Bangkok dental prospects to outreach list",
    status: "Open",
    priority: "Medium",
    dueDate: "2026-03-22",
    owner: "Yan",
    ownerType: "Human",
    linkedOpportunityOrClient: "Bangkok Aesthetic Clinics Outreach",
    notes: "Expand the list with clinics matching pricing and high-intent lead-gen profile.",
    details: "This is a campaign-support task rather than a client delivery task.",
    source: "manual",
    nextAction: false,
    category: "Pipeline",
    overdue: false,
  },
  {
    id: "task-005",
    title: "Prototype deck sent - follow up Titan Roofing",
    status: "Open",
    priority: "High",
    dueDate: "2026-03-19",
    owner: "Yan",
    ownerType: "Human",
    linkedOpportunityOrClient: "Titan Roofing Group",
    notes: "Follow-up date has passed without reply.",
    details: "Proposal/prototype has been out for 3 days with no response.",
    source: "manual",
    nextAction: true,
    category: "Pipeline",
    overdue: true,
  },
  {
    id: "task-006",
    title: "Create outreach summary note for Bangkok aesthetics campaign",
    status: "In Progress",
    priority: "Low",
    dueDate: "2026-03-24",
    owner: "Yan",
    ownerType: "Human",
    linkedOpportunityOrClient: "Bangkok Aesthetic Clinics Outreach",
    notes: "Capture what segments are responding and refine target criteria.",
    details: "Helps tune follow-up messaging and prioritization.",
    source: "manual",
    nextAction: false,
    category: "Internal",
    overdue: false,
  },
  {
    id: "task-007",
    title: "Approve website direction before build spec",
    status: "Review",
    priority: "High",
    dueDate: "2026-03-21",
    owner: "Yan",
    ownerType: "Human",
    linkedProject: "Harbour Living Website Refresh",
    linkedWorkflow: "Website",
    linkedOpportunityOrClient: "Harbour Living",
    notes: "Review style references and section strategy before implementation handoff.",
    details: "This is a project-stage approval gate.",
    source: "system",
    nextAction: true,
    category: "Project",
    overdue: false,
  },
  {
    id: "task-008",
    title: "Await pricing clarification from Apex Property",
    status: "Open",
    priority: "Medium",
    dueDate: "2026-03-18",
    owner: "Yan",
    ownerType: "Human",
    linkedProject: "Apex Investor Automation",
    linkedWorkflow: "Solution Design",
    linkedOpportunityOrClient: "Apex Property Partners",
    notes: "Project cannot move from solution design to prototype without final packaging decision.",
    details: "Needs client-side confirmation before next step.",
    source: "manual",
    nextAction: false,
    category: "Project",
    overdue: true,
  },
  {
    id: "task-009",
    title: "Create missed-call recovery draft for Peach Aesthetics",
    status: "Open",
    priority: "Medium",
    dueDate: "2026-03-23",
    owner: "System",
    ownerType: "System",
    linkedProject: "Peach Aesthetics Evaluation",
    linkedWorkflow: "Evaluation",
    linkedOpportunityOrClient: "Peach Aesthetics",
    notes: "System-generated task from evaluation workflow.",
    details: "Draft solution concept needed before discovery follow-up.",
    source: "system",
    nextAction: false,
    category: "Project",
    overdue: false,
  },
  {
    id: "task-010",
    title: "Mark closed-lost notes for Ember Fitness",
    status: "Complete",
    priority: "Low",
    dueDate: "2026-03-18",
    owner: "Yan",
    ownerType: "Human",
    linkedOpportunityOrClient: "Ember Fitness Collective",
    notes: "Commercial notes already saved after no-fit outcome.",
    details: "Completed admin cleanup.",
    source: "manual",
    nextAction: false,
    category: "Pipeline",
    overdue: false,
  },
];

export const projects: ProjectRecord[] = [
  {
    projectId: "proj-001",
    projectName: "Solara Dental Growth System",
    projectStatus: "Open",
    currentPhase: "Prototype direction under review",
    ownerRole: "Yan",
    linkedClient: "Solara Dental Studio",
    blockers: 0,
    nextProjectAction: "Approve prototype direction and package the proposal.",
    linkedTasks: 3,
    progress: 46,
    projectStage: "Prototype",
    taskHealthStatus: "Review",
    projectCategory: "Client",
    projectTrack: "Service Delivery",
    summary: "Evaluation work has been completed and the engagement has moved into prototype shaping.",
    nextDueDate: "2026-03-20",
  },
  {
    projectId: "proj-002",
    projectName: "Verity Wealth Evaluation",
    projectStatus: "Open",
    currentPhase: "Discovery findings and evaluation",
    ownerRole: "Yan",
    linkedClient: "Verity Wealth Partners",
    blockers: 0,
    nextProjectAction: "Convert discovery notes into a recommended solution path.",
    linkedTasks: 2,
    progress: 28,
    projectStage: "Evaluation",
    taskHealthStatus: "In Progress",
    projectCategory: "Client",
    projectTrack: "Service Delivery",
    summary: "Pre-proposal commercial project created because meaningful evaluation work is already underway.",
    nextDueDate: "2026-03-20",
  },
  {
    projectId: "proj-003",
    projectName: "Harbour Living Website Refresh",
    projectStatus: "Open",
    currentPhase: "Visual direction approved pending build spec",
    ownerRole: "Yan",
    linkedClient: "Harbour Living",
    blockers: 0,
    nextProjectAction: "Finalize section strategy and build spec.",
    linkedTasks: 4,
    progress: 61,
    projectStage: "Website / Asset Build",
    taskHealthStatus: "Review",
    projectCategory: "Client",
    projectTrack: "Service Delivery",
    summary: "Website project with clear delivery scope and active review gates.",
    nextDueDate: "2026-03-21",
  },
  {
    projectId: "proj-004",
    projectName: "Apex Investor Automation",
    projectStatus: "Open",
    currentPhase: "Commercial packaging needs final pricing clarification",
    ownerRole: "Yan",
    linkedClient: "Apex Property Partners",
    blockers: 1,
    nextProjectAction: "Resolve pricing clarification and move into prototype.",
    linkedTasks: 2,
    progress: 39,
    projectStage: "Solution Design",
    taskHealthStatus: "Overdue",
    projectCategory: "Client",
    projectTrack: "Service Delivery",
    summary: "Solution design is mostly complete but blocked by unresolved commercial details.",
    nextDueDate: "2026-03-18",
  },
  {
    projectId: "proj-005",
    projectName: "FlowOps Aesthetic Offer Sprint",
    projectStatus: "Closed / Archived",
    currentPhase: "Archived after offer consolidation",
    ownerRole: "Yan",
    linkedClient: "Internal",
    blockers: 0,
    nextProjectAction: "Archived",
    linkedTasks: 0,
    progress: 100,
    projectStage: "Closed / Archived",
    taskHealthStatus: "Open",
    projectCategory: "Internal",
    projectTrack: "Offer Development",
    summary: "Retained as a closed internal reference.",
    nextDueDate: "",
  },
];

export const opportunities: OpportunityRecord[] = [
  {
    opportunityId: "opp-001",
    opportunityName: "Smile Dental Bangkok",
    pipelineStage: "Initial Contact",
    owner: "Yan",
    linkedClient: "Dental automation prospect",
    nextOpportunityAction: "Send first follow-up and invite discovery.",
    classificationStatus: "Prospect engaged",
    linkedTasks: 1,
    pipelineValue: "$3,000",
    recordType: "contact",
    campaignName: "Bangkok Aesthetic Clinics Outreach",
    summary: "Prospect has responded lightly to first-touch outreach and is warm enough for follow-up.",
    nextStepDueDate: "2026-03-21",
    linkedProjectName: "",
    urgent: false,
    status: "Open",
  },
  {
    opportunityId: "opp-002",
    opportunityName: "Solara Dental Studio",
    pipelineStage: "Prototype/Proposal Sent",
    owner: "Yan",
    linkedClient: "Dental lead capture and follow-up automation",
    nextOpportunityAction: "Review prototype direction and package final proposal.",
    classificationStatus: "Proposal active",
    linkedTasks: 3,
    pipelineValue: "$6,500",
    recordType: "opportunity",
    campaignName: "Bangkok Aesthetic Clinics Outreach",
    summary: "Discovery completed and the engagement is far enough along that a project already exists.",
    nextStepDueDate: "2026-03-20",
    linkedProjectName: "Solara Dental Growth System",
    urgent: false,
    status: "Review",
  },
  {
    opportunityId: "opp-003",
    opportunityName: "Verity Wealth Partners",
    pipelineStage: "Discovery",
    owner: "Yan",
    linkedClient: "Investor enquiry and conversion system",
    nextOpportunityAction: "Turn discovery insights into a recommended solution.",
    classificationStatus: "Discovery active",
    linkedTasks: 2,
    pipelineValue: "$8,500",
    recordType: "opportunity",
    summary: "Discovery is active and an evaluation project has already been opened to structure the work.",
    nextStepDueDate: "2026-03-20",
    linkedProjectName: "Verity Wealth Evaluation",
    urgent: false,
    status: "In Progress",
  },
  {
    opportunityId: "opp-004",
    opportunityName: "Titan Roofing Group",
    pipelineStage: "In Negotiation",
    owner: "Yan",
    linkedClient: "Lead qualification and proposal follow-up system",
    nextOpportunityAction: "Follow up overdue proposal/prototype thread.",
    classificationStatus: "Negotiation active",
    linkedTasks: 1,
    pipelineValue: "$9,000",
    recordType: "opportunity",
    summary: "Commercial negotiation is live and follow-up is now overdue.",
    nextStepDueDate: "2026-03-19",
    linkedProjectName: "",
    urgent: true,
    status: "Open",
  },
  {
    opportunityId: "opp-005",
    opportunityName: "Peach Aesthetics",
    pipelineStage: "Discovery",
    owner: "Yan",
    linkedClient: "Missed-call recovery and front-desk automation",
    nextOpportunityAction: "Draft evaluation and solution direction.",
    classificationStatus: "Discovery complete, evaluation started",
    linkedTasks: 1,
    pipelineValue: "$4,200",
    recordType: "opportunity",
    campaignName: "Bangkok Aesthetic Clinics Outreach",
    summary: "Good fit prospect that has crossed into project-worthy evaluation work.",
    nextStepDueDate: "2026-03-23",
    linkedProjectName: "Peach Aesthetics Evaluation",
    urgent: false,
    status: "Open",
  },
  {
    opportunityId: "opp-006",
    opportunityName: "Harbour Living",
    pipelineStage: "Closed Won",
    owner: "Yan",
    linkedClient: "Website refresh and conversion architecture",
    nextOpportunityAction: "Continue delivery in project workflow.",
    classificationStatus: "Won",
    linkedTasks: 4,
    pipelineValue: "$7,200",
    recordType: "opportunity",
    summary: "Closed-won commercial record linked to an active website delivery project.",
    nextStepDueDate: "2026-03-21",
    linkedProjectName: "Harbour Living Website Refresh",
    urgent: false,
    status: "In Progress",
  },
  {
    opportunityId: "opp-007",
    opportunityName: "Ember Fitness Collective",
    pipelineStage: "Closed Lost",
    owner: "Yan",
    linkedClient: "Lead recovery and nurture concept",
    nextOpportunityAction: "Archive and retain notes.",
    classificationStatus: "Lost",
    linkedTasks: 0,
    pipelineValue: "-$2,000",
    recordType: "opportunity",
    summary: "No-fit outcome; retained for reporting only.",
    nextStepDueDate: "",
    linkedProjectName: "",
    urgent: false,
    status: "Complete",
  },
];

export const workflows: WorkflowRecord[] = [
  {
    id: "wf-001",
    activeWorkflow: "Prototype",
    workflowStatus: "Review",
    currentStep: "Prototype direction approval",
    blockingIssues: [],
    nextWorkflowCandidate: "Proposal packaging",
    linkedProject: "Solara Dental Growth System",
    projectStage: "Prototype",
    nextDueDate: "2026-03-20",
    leftSummary: [
      "Client: Solara Dental Studio",
      "Commercial stage: Prototype/Proposal Sent",
      "Tasks: 3 linked",
    ],
    nodes: [
      { id: "wf-001-n1", name: "Research", type: "Project Stage", status: "Complete", summary: "Research and problem framing completed." },
      { id: "wf-001-n2", name: "Evaluation", type: "Project Stage", status: "Complete", summary: "Need and likely solution direction validated." },
      { id: "wf-001-n3", name: "Prototype", type: "Project Stage", status: "Active", summary: "Prototype direction is under active review." },
      { id: "wf-001-n4", name: "Website / Asset Build", type: "Project Stage", status: "Queued", summary: "Only needed if direction moves into full build work." },
    ],
  },
  {
    id: "wf-002",
    activeWorkflow: "Evaluation",
    workflowStatus: "Active",
    currentStep: "Discovery findings synthesis",
    blockingIssues: [],
    nextWorkflowCandidate: "Solution Design",
    linkedProject: "Verity Wealth Evaluation",
    projectStage: "Evaluation",
    nextDueDate: "2026-03-20",
    leftSummary: [
      "Client: Verity Wealth Partners",
      "Commercial stage: Discovery",
      "Tasks: 2 linked",
    ],
    nodes: [
      { id: "wf-002-n1", name: "Research", type: "Project Stage", status: "Complete", summary: "Discovery material gathered and organized." },
      { id: "wf-002-n2", name: "Evaluation", type: "Project Stage", status: "Active", summary: "Assessment is in progress." },
      { id: "wf-002-n3", name: "Solution Design", type: "Project Stage", status: "Queued", summary: "Will begin after evaluation is packaged." },
      { id: "wf-002-n4", name: "Prototype", type: "Project Stage", status: "Queued", summary: "Optional next step if opportunity remains warm." },
    ],
  },
  {
    id: "wf-003",
    activeWorkflow: "Website",
    workflowStatus: "Review",
    currentStep: "Approve website direction before build spec",
    blockingIssues: [],
    nextWorkflowCandidate: "Implementation",
    linkedProject: "Harbour Living Website Refresh",
    projectStage: "Website / Asset Build",
    nextDueDate: "2026-03-21",
    leftSummary: [
      "Client: Harbour Living",
      "Commercial stage: Closed Won",
      "Tasks: 4 linked",
    ],
    nodes: [
      { id: "wf-003-n1", name: "Solution Design", type: "Project Stage", status: "Complete", summary: "Offer and direction have been packaged." },
      { id: "wf-003-n2", name: "Website / Asset Build", type: "Project Stage", status: "Active", summary: "Structure and visual direction are in review." },
      { id: "wf-003-n3", name: "Implementation", type: "Project Stage", status: "Queued", summary: "Build will begin after approval." },
      { id: "wf-003-n4", name: "Review / Approval", type: "Project Stage", status: "Queued", summary: "Final pre-launch review remains ahead." },
    ],
  },
  {
    id: "wf-004",
    activeWorkflow: "Solution Design",
    workflowStatus: "Blocked",
    currentStep: "Resolve pricing clarification",
    blockingIssues: ["Client pricing clarification is overdue and is blocking prototype packaging."],
    nextWorkflowCandidate: "Prototype",
    linkedProject: "Apex Investor Automation",
    projectStage: "Solution Design",
    nextDueDate: "2026-03-18",
    leftSummary: [
      "Client: Apex Property Partners",
      "Commercial stage: In Negotiation",
      "Tasks: 2 linked",
    ],
    nodes: [
      { id: "wf-004-n1", name: "Evaluation", type: "Project Stage", status: "Complete", summary: "Need and structure are known." },
      { id: "wf-004-n2", name: "Solution Design", type: "Project Stage", status: "Blocked", summary: "Blocked on pricing and packaging clarification." },
      { id: "wf-004-n3", name: "Prototype", type: "Project Stage", status: "Queued", summary: "Will start after clarification." },
      { id: "wf-004-n4", name: "Implementation", type: "Project Stage", status: "Queued", summary: "Delivery path not yet opened." },
    ],
  },
];

export const headerState: HeaderState = {
  activeProject: "Solara Dental Growth System",
  activeWorkflow: "Prototype",
  nextActionCount: tasks.filter((task) => task.nextAction && !["Complete", "Completed", "Archived"].includes(task.status)).length,
  pendingApprovals: tasks.filter((task) => task.status === "Review").length,
  blockers: projects.filter((project) => project.taskHealthStatus === "Overdue").length,
  overdueCount: tasks.filter((task) => task.overdue).length,
  reviewCount: tasks.filter((task) => task.status === "Review").length,
};

export const agencyOverview: AgencyOverviewSummary = {
  recurringRevenue: 14200,
  oneOffRevenue: 11800,
  activeClientsRevenue: 26000,
  clientPipelineValue: opportunities
    .filter((item) => !["Closed Lost"].includes(item.pipelineStage))
    .reduce((sum, item) => sum + Number(item.pipelineValue.replace(/[$,]/g, "")), 0),
  activeClientsCount: 4,
  openOpportunitiesCount: opportunities.filter((item) => !["Closed Won", "Closed Lost"].includes(item.pipelineStage)).length,
  openProjectsCount: projects.filter((project) => project.projectStage !== "Closed / Archived").length,
  expiredClientsCount: 2,
  expiredClientsRevenue: 4200,
  openTasksCount: tasks.filter((task) => !["Complete", "Completed", "Archived"].includes(task.status)).length,
  overdueTasksCount: tasks.filter((task) => task.overdue).length,
  reviewTasksCount: tasks.filter((task) => task.status === "Review").length,
};

export const deliveryProgress: DeliveryProgressItem[] = projects
  .filter((project) => project.projectStage !== "Closed / Archived")
  .map((project) => ({
    label: project.projectName,
    stage: project.projectStage,
    progress: project.progress,
  }));

export const pipelineStageSummary: PipelineStageSummary[] = [
  "Initial Contact",
  "Discovery",
  "Prototype/Proposal Sent",
  "In Negotiation",
  "Closed Won",
  "Closed Lost",
].map((stage) => {
  const records = opportunities.filter((item) => item.pipelineStage === stage);
  return {
    stage,
    count: records.length,
    revenue: records.reduce((sum, item) => sum + Number(item.pipelineValue.replace(/[$,]/g, "")), 0),
  };
});

export const taskSummary = {
  open: tasks.filter((task) => !["Complete", "Completed", "Archived"].includes(task.status) && !task.overdue).length,
  overdue: tasks.filter((task) => task.overdue).length,
  queue: tasks.filter((task) => !["Complete", "Completed", "Archived"].includes(task.status)).length,
};

export const focusTasks = tasks
  .filter((task) => !["Complete", "Completed", "Archived"].includes(task.status))
  .sort((left, right) => {
    const leftScore = (left.nextAction ? 10 : 0) + priorityRank[left.priority] + (left.overdue ? 5 : 0);
    const rightScore = (right.nextAction ? 10 : 0) + priorityRank[right.priority] + (right.overdue ? 5 : 0);
    return rightScore - leftScore;
  });

export const skillFactoryReview: ReviewItem[] = [];
export const knowledgeReview: ReviewItem[] = [];

export const activityFeed: ActivityItem[] = [
  {
    id: "act-001",
    activityType: "Pipeline Update",
    activityTime: "12 min ago",
    linkedDomain: "Pipeline",
    linkedRecord: "opp-001",
    operatorOrSystemSource: "Yan",
    summary: "Smile Dental Bangkok moved deeper into initial-contact follow-up with discovery invitation planned.",
  },
  {
    id: "act-002",
    activityType: "Workflow Review",
    activityTime: "27 min ago",
    linkedDomain: "Workflow",
    linkedRecord: "wf-001",
    operatorOrSystemSource: "Yan",
    summary: "Prototype direction for Solara Dental flagged for review before proposal send.",
  },
  {
    id: "act-003",
    activityType: "Project Pressure",
    activityTime: "43 min ago",
    linkedDomain: "Projects",
    linkedRecord: "proj-004",
    operatorOrSystemSource: "System",
    summary: "Apex Investor Automation now shows overdue pressure because pricing clarification has slipped.",
  },
];

export const metrics: MetricCard[] = [
  {
    id: "metric-001",
    label: "Open Opportunities",
    value: String(agencyOverview.openOpportunitiesCount),
    trend: "Current month snapshot",
    context: "High-level commercial snapshot for Agency Overview.",
  },
  {
    id: "metric-002",
    label: "Overdue Tasks",
    value: String(agencyOverview.overdueTasksCount),
    trend: "Needs close monitoring",
    context: "Count of overdue items across projects, pipeline, and internal work.",
  },
  {
    id: "metric-003",
    label: "Open Projects",
    value: String(agencyOverview.openProjectsCount),
    trend: "Delivery portfolio",
    context: "Projects currently active and not closed or archived.",
  },
  {
    id: "metric-004",
    label: "Review Queue",
    value: String(agencyOverview.reviewTasksCount),
    trend: "Approval pressure",
    context: "Tasks currently waiting for review or approval.",
  },
];
